### ISSUE TITLE
conflict with module subscription from odoo

### ISSUE THREAD

**Issue by eugen-don** [OCA/queue#21]
Hi guys, i just pulled a fresh clone of v. 10.0 from git of both odoo and the queue repo, just to make sure i have no old versions.

Now heres the error i get if i install queue_job after installing the module subscription:

Traceback (most recent call last):
  File "/opt/Software/10/srv/Software/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/Software/10/srv/Software/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/Software/10/srv/Software/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/Software/10/srv/Software/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/Software/10/srv/Software/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/Software/10/srv/Software/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/Software/10/srv/Software/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/Software/10/srv/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/Software/10/srv/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/Software/10/srv/Software/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/Software/10/srv/Software/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/Software/10/srv/Software/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/Software/10/srv/Software/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/Software/10/srv/Software/modules/registry.py", line 82, in new
    Software.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/Software/10/srv/Software/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/Software/10/srv/Software/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/Software/10/srv/Software/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/Software/10/srv/Software/modules/registry.py", line 318, in init_models
    model._auto_end()
  File "/opt/Software/10/srv/addons/subscription/models/subscription.py", line 64, in _auto_end
    self.env.cr.execute("ALTER TABLE %s DROP CONSTRAINT %s" % (self._table, '%s_cron_id_fkey' % self._table))
  File "/opt/Software/10/srv/Software/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/Software/10/srv/Software/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: constraint "subscription_subscription_cron_id_fkey" of relation "subscription_subscription" does not exist

Is it just me or does this look like its a problem with the subscription module itself?

Any idea?

**Comment by pedrobaeza** [comment]
This is very strange. Please try again in a fresh installation.

**Comment by eugen-don** [comment]
on runbot both modules work fine.

Seems its my install thats out of date...
