### ISSUE TITLE
[13.0] queue_job: error when upgrade base

### ISSUE THREAD

**Issue by abdallamohamedcore** [OCA/queue#227]
Hello
I have issue appear when i try to upgrade `base` if module `queue_job` is installed as below
```python
2020-05-18 08:38:47,937 101 INFO migration-database-mig-test-1102394 odoo.addons.base.models.ir_model: Deleting 1906@ir.model.fields.selection (base.selection__ir_model_fields__ttype__job_serialized) 
2020-05-18 08:38:47,940 101 ERROR migration-database-mig-test-1102394 odoo.sql_db: bad query: UPDATE "ir_model_fields" SET "ttype"=NULL WHERE "ttype"='job_serialized'
ERROR: null value in column "ttype" violates not-null constraint
DETAIL:  Failing row contains (10232, kwargs, null, queue.job, null, null, null, 508, Kwargs, null, null, t, null, null, f, t, f, f, null, base, null, null, t, null, null, null, null, null, t, null, null, 1, 2019-08-08 20:09:28.850875, null, null, t, null).
 
2020-05-18 08:38:47,946 101 WARNING migration-database-mig-test-1102394 odoo.modules.loading: Transient module states were reset 
2020-05-18 08:38:47,947 101 ERROR migration-database-mig-test-1102394 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 472, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 1986, in _process_end
    record.unlink()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 1208, in unlink
    self.env.cr.execute(query, [selection.value])
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 164, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 241, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "ttype" violates not-null constraint
DETAIL:  Failing row contains (10232, kwargs, null, queue.job, null, null, null, 508, Kwargs, null, null, t, null, null, f, t, f, f, null, base, null, null, t, null, null, null, null, null, t, null, null, 1, 2019-08-08 20:09:28.850875, null, null, t, null).

**Comment by guewen** [comment]
Hello,

I could not reproduce it on my end by installing queue_job, then upgrading base.
Do you have steps to reproduce?

**Comment by guewen** [comment]
I had the same error in a build. A correction is coming.

```
2020-08-11 13:10:51,932 167 INFO sample odoo.modules.loading: 297 modules loaded in 529.51s, 0 queries
2020-08-11 13:10:53,159 167 INFO sample odoo.addons.base.models.ir_model: Deleting 4@ir.model.fields.selection (base.selection__ir_model_fields__ttype__job_serialized)
2020-08-11 13:10:53,163 167 ERROR sample odoo.sql_db: bad query: UPDATE "ir_model_fields" SET "ttype"=NULL WHERE "ttype"='job_serialized'
ERROR: null value in column "ttype" violates not-null constraint
DETAIL:  Failing row contains (4296, record_ids, null, queue.job, null, null, null, 266, Record, null, null, t, null, null, f, t, f, f, null, base, null, null, t, null, null, null, null, null, t, null, null, 1, 2020-08-11 13:03:09.913127, null, null).

2020-08-11 13:10:53,168 167 WARNING sample odoo.modules.loading: Transient module states were reset
2020-08-11 13:10:53,170 167 ERROR sample odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/src/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/src/odoo/modules/loading.py", line 472, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/odoo/src/odoo/addons/base/models/ir_model.py", line 1990, in _process_end
    record.unlink()
  File "/odoo/src/odoo/addons/base/models/ir_model.py", line 1208, in unlink
    self.env.cr.execute(query, [selection.value])
  File "/odoo/src/odoo/sql_db.py", line 168, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/src/odoo/sql_db.py", line 245, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "ttype" violates not-null constraint
DETAIL:  Failing row contains (4296, record_ids, null, queue.job, null, null, null, 266, Record, null, null, t, null, null, f, t, f, f, null, base, null, null, t, null, null, null, null, null, t, null, null, 1, 2020-08-11 13:03:09.913127, null, null).
```

**Comment by guewen** [comment]
@abdallamohamedcore did you encounter this with Odoo 13.0 or a more ancient version?
