### ISSUE TITLE
queue_job - OSError: [WinError 10038] An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by chrisandrewmann** [OCA/queue#240]
I understand this was raised previously in this issue #65, however I'm experiencing this now as a developer relying on Windows machines for Odoo debugging via Visual Studio.

Prior to 5th June 2020, queue_job would throw the error in the odoo log file, but jobs would still succeed when called regardless. Since the latest commits after 5th June it appears #208 now forces the module to run in a separate thread, even though Odoo config is set to disable workers.
For me this makes it now impossible to debug and test the queue_job module on a Windows machine as the error blocks all code for jobs executing. 
Hoping someone has a workaround or fix for this please? For now I've reverted to using the older version.

**Error from Odoo log prior to 5th June 2020**
```
ERROR ? odoo.addons.queue_job.jobrunner.runner: exception: sleeping 5s and retrying
Traceback (most recent call last):
  File "\queue_job\jobrunner\runner.py", line 494, in run self.wait_notification()
  File "\queue_job\jobrunner\runner.py", line 469, in wait_notification
    conns, _, _ = select.select(conns, [], [], timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

**Error in current version**
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "\queue_job\jobrunner\runner.py", line 524, in run self.wait_notification()
  File "\queue_job\jobrunner\runner.py", line 499, in wait_notification
    conns, _, _ = select.select(conns, [], [], timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket 

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "\queue_job\jobrunner\__init__.py", line 44, in run self.runner.run()
  File "\queue_job\jobrunner\runner.py", line 529, in run
    if isinstance(e, select.error) and e[0] == 4:
TypeError: 'OSError' object is not subscriptable
```

**Comment by guewen** [comment]
@chrisandrewmann Thanks for the detailed report! Could you test #241?
