### ISSUE TITLE
Queue Job Error

### ISSUE THREAD

**Issue by hieulucky111** [OCA/queue#36]
I have this issue when i start odoo with option `server_wide_modules = web,web_kanban_gauge,queue_job`

```Traceback (most recent call last):
  File "/opt/odoo/code/projects/odoo11/odoo/odoo/service/server.py", line 869, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/opt/odoo/code/projects/odoo11/odoo/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/opt/odoo/code/projects/odoo11/odoo/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
  File "/opt/odoo/code/projects/odoo11/addons/oca-queue/queue_job/models/__init__.py", line 4, in <module>
    from . import queue_job
  File "/opt/odoo/code/projects/odoo11/addons/oca-queue/queue_job/models/queue_job.py", line 21, in <module>
    class QueueJob(models.Model):
  File "/opt/odoo/code/projects/odoo11/addons/oca-queue/queue_job/models/queue_job.py", line 45, in QueueJob
    record_ids = fields.Serialized(readonly=True)
AttributeError: module 'odoo.fields' has no attribute 'Serialized'

**Comment by hieulucky111** [comment]
I try to fix by add this line `from odoo.addons.base_sparse_field.models.fields import Serialized` and change `record_ids = fields.Serialized(readonly=True)` to `record_ids = Serialized(readonly=True)`

**Comment by guewen** [comment]
In v11 you have to use `server_wide_modules = web,web_kanban_gauge,base_sparse_field,queue_job`
