### ISSUE TITLE
Error OSERROR [WinError 10038] in odoo 14, on queue_job\jobrunner\runner.py 

### ISSUE THREAD

**Issue by landlogicit** [OCA/queue#447]
Hi, i have this error on console log:

2022-07-12 08:34:48,431 22928 ERROR ? odoo.addons.queue_job.jobrunner.runner: exception: sleeping 5s and retrying 
Traceback (most recent call last):
  File "c:\users\lorenzo\pycharmprojects\odoo-14-dev\queue_job\jobrunner\runner.py", line 507, in run
    self.wait_notification()
  File "c:\users\lorenzo\pycharmprojects\odoo-14-dev\queue_job\jobrunner\runner.py", line 482, in wait_notification
    conns, _, _ = select.select(conns, [], [], timeout)
OSError: [WinError 10038] Tentativo di operazione su un elemento diverso dal socket
2022-07-12 08:34:48,675 22928 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres

**Comment by yxj1028530975** [comment]
I also made this error on odoo15. Have you solved it?

**Comment by landlogicit** [comment]
Please check this bug

**Comment by roman-marchenko-advisability** [comment]
Aug 2023, v15, problem not solved

**Comment by vlyubimov** [comment]
Aug 2023, problem not solved

I have this problem too
