### ISSUE TITLE
[16.0][queue_job] "base_sparse_field" is missing on Odoo 16

### ISSUE THREAD

**Issue by yibudak** [OCA/queue#491]
https://github.com/OCA/queue/blob/ea20a97f43b5af61b4b11baa56f3f547fcb518d2/queue_job/__manifest__.py#L10

It seems like there is no migration process for base_sparse_field (which is located in OCA). Also there is no implementation of that module in Odoo 16 source code.

Is this a mistake?
Error log:
`2022-12-23 08:44:12,289 343040 INFO 16test1 odoo.modules.graph: module queue_job: Unmet dependencies: base_sparse_field `

Another error log:
```

Traceback (most recent call last):
  File "/opt/odoo/v16/odoo-server/odoo/http.py", line 1965, in __call__
    response = request._serve_db()
  File "/opt/odoo/v16/odoo-server/odoo/http.py", line 1550, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/v16/odoo-server/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/v16/odoo-server/odoo/http.py", line 1579, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/v16/odoo-server/odoo/http.py", line 1692, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/v16/odoo-server/addons/website/models/ir_http.py", line 227, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/v16/odoo-server/odoo/addons/base/models/ir_http.py", line 140, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/v16/odoo-server/odoo/http.py", line 674, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/v16/addons/queue_job/controllers/main.py", line 104, in runjob
    self._try_perform_job(env, job)
  File "/opt/odoo/v16/addons/queue_job/controllers/main.py", line 36, in _try_perform_job
    job.perform()
  File "/opt/odoo/v16/addons/queue_job/job.py", line 517, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/opt/odoo/v16/addons/connector_odoo/models/odoo_binding/common.py", line 65, in import_batch
    return importer.run(filters=filters, force=backend.force)
  File "/opt/odoo/v16/addons/connector_odoo/models/product_pricelist/importer.py", line 122, in run
    self._import_record(pricelist_id.id, job_options=job_options)
  File "/opt/odoo/v16/addons/connector_odoo/models/product_pricelist/importer.py", line 106, in _import_record
    return super()._import_record(external_id, job_options=job_options, force=force)
  File "/opt/odoo/v16/addons/connector_odoo/components/importer.py", line 332, in _import_record
    delayable.import_record(
  File "/opt/odoo/v16/addons/queue_job/delay.py", line 614, in _delay_delayable
    getattr(self.delayable, name)(*args, **kwargs).delay()
  File "/opt/odoo/v16/addons/queue_job/delay.py", line 532, in delay
    self._graph.delay()
  File "/opt/odoo/v16/addons/queue_job/delay.py", line 300, in delay
    vertex._generated_job.store()
  File "/opt/odoo/v16/addons/queue_job/job.py", line 582, in store
    job_model.with_context(_job_edit_sentinel=edit_sentinel).sudo().create(
  File "<decorator-gen-29>", line 2, in create
  File "/opt/odoo/v16/odoo-server/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/v16/addons/queue_job/models/queue_job.py", line 252, in create
    ).create(vals_list)
  File "<decorator-gen-142>", line 2, in create
  File "/opt/odoo/v16/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/v16/odoo-server/addons/mail/models/mail_thread.py", line 258, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-130>", line 2, in create
  File "/opt/odoo/v16/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/v16/addons/component_event/models/base.py", line 102, in create
    records = super(Base, self).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/opt/odoo/v16/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/v16/odoo-server/odoo/addons/base/models/ir_fields.py", line 657, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/v16/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/v16/odoo-server/odoo/models.py", line 3925, in create
    records = self._create(data_list)
  File "/opt/odoo/v16/odoo-server/odoo/models.py", line 4083, in _create
    colval = field.convert_to_column(stored[fname], self, stored)
  File "/opt/odoo/v16/addons/queue_job/fields.py", line 55, in convert_to_column
    return self.convert_to_cache(value, record, validate=validate)
  File "/opt/odoo/v16/addons/queue_job/fields.py", line 60, in convert_to_cache
    return json.dumps(value, cls=JobEncoder)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/odoo/v16/addons/queue_job/fields.py", line 96, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WorkContext is not JSON serializable

```

**Comment by yibudak** [comment]
@guewen

**Comment by yibudak** [comment]
nvm. my bad.
