### ISSUE TITLE
Random message: Unable to use a closed cursor

### ISSUE THREAD

**Issue by flachica** [OCA/queue#494]
## Module
queue_job

## Describe the bug
Sometimes I get an exception with the message "Cannot use a closed cursor". I attached the trace. I'm still not clear under what circumstances it occurs

## To Reproduce
I haven't yet found a rule that is met for the error to be raised. I have defined 12 channels for the jobs

```
[queue_job]
channels = root:12
``` 

**Affected versions**: 15.0

1. Run jobs queue

## Log
```
2022-12-27 11:54:36,761 3391042 INFO ? odoo.addons.queue_job.jobrunner.runner: asking Odoo to run job 4159f963-3329-4da0-9fa1-7870850cbb84 on db odoo 
2022-12-27 11:54:36,766 3391026 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/ubuntu/www/odoo_src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 810, in dispatch
    r = self._call_function(**self.params)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/ubuntu/www/odoo_src/queue/queue_job/controllers/main.py", line 149, in runjob
    self._enqueue_dependent_jobs(env, job)
  File "/home/ubuntu/www/odoo_src/queue/queue_job/controllers/main.py", line 47, in _enqueue_dependent_jobs
    job.enqueue_waiting()
  File "/home/ubuntu/www/odoo_src/queue/queue_job/job.py", line 566, in enqueue_waiting
    self.env.cr.execute(sql, (PENDING, self.uuid, DONE, WAIT_DEPENDENCIES))
  File "<decorator-gen-3>", line 2, in execute
    
  File "/home/ubuntu/www/odoo_src/odoo/odoo/sql_db.py", line 89, in check
    raise psycopg2.OperationalError('Unable to use a closed cursor.')
```

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/service/wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/service/wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 1341, in __call__
    return self.dispatch(environ, start_response)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 1307, in __call__
    return self.app(environ, start_wrapped)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 1536, in dispatch
    result = ir_http._dispatch()
  File "/home/ubuntu/www/odoo_src/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/ubuntu/www/odoo_src/odoo/addons/website/models/ir_http.py", line 198, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/home/ubuntu/www/odoo_src/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/ubuntu/www/odoo_src/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/ubuntu/www/odoo_src/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/home/ubuntu/www/odoo_src/odoo/addons/http_routing/models/ir_http.py", line 519, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/home/ubuntu/www/odoo_src/odoo/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/home/ubuntu/www/odoo_src/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/home/ubuntu/www/odoo_src/odoo/addons/http_routing/models/ir_http.py", line 620, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 748, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/ubuntu/www/odoo_src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.OperationalError: Unable to use a closed cursor. - - -
2022-12-27 11:54:36,773 3391032 INFO odoo odoo.modules.registry: Invalidating all model caches after database signaling. 
```

**Comment by jzahid** [comment]
Hi i have the same issue in v16 , it seems to be random, Job start correctly and the for no reason , crashes and then restarts again. Here is the stacktrace

    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1613, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1726, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 149, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo-extra-addons/queue_job/controllers/main.py", line 149, in runjob
    self._enqueue_dependent_jobs(env, job)
  File "/opt/odoo-extra-addons/queue_job/controllers/main.py", line 47, in _enqueue_dependent_jobs
    job.enqueue_waiting()
  File "/opt/odoo-extra-addons/queue_job/job.py", line 566, in enqueue_waiting
    self.env.cr.execute(sql, (PENDING, self.uuid, DONE, WAIT_DEPENDENCIES))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 316, in execute
    _logger.error("bad query: %s\nERROR: %s", tools.ustr(self._obj.query or query), e)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 462, in __getattr__
    raise psycopg2.InterfaceError("Cursor already closed")
psycopg2.InterfaceError: Cursor already closed
