### ISSUE TITLE
KeyError: 'socket' After install queue.job in odoo 16.0

### ISSUE THREAD

**Issue by RichardThunder** [OCA/queue#549]
## Module
queue_job

## Describe the bug
After I install queue_job in odoo16.0, I got these outputs from terminal. However, I could still use odoo.
This  exception did not stop odoo and its apps could work properly, but outputs many times when I use odoo in browser, which outputs every 2 seconds.

"mdc_local" is name of DB.
```
2023-06-28 04:58:49,132 5484 INFO mdc_local werkzeug: 127.0.0.1 - - [28/Jun/2023 04:58:49] "GET /websocket HTTP/1.1" 500 - 1 0.000 0.004
2023-06-28 04:59:10,272 5484 ERROR mdc_local odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/Users/richard/code/odoo-16.0/odoo/http.py", line 1988, in __call__
    response = request._serve_db()
  File "/Users/richard/code/odoo-16.0/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/Users/richard/code/odoo-16.0/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/Users/richard/code/odoo-16.0/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/Users/richard/code/odoo-16.0/odoo/http.py", line 1724, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/Users/richard/code/odoo-16.0/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/Users/richard/code/odoo-16.0/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/Users/richard/code/odoo-16.0/odoo/addons/bus/controllers/websocket.py", line 23, in websocket
    return WebsocketConnectionHandler.open_connection(request)
  File "/Users/richard/code/odoo-16.0/odoo/addons/bus/websocket.py", line 814, in open_connection
    Websocket(request.httprequest.environ['socket'], request.session),
KeyError: 'socket'
```
## To Reproduce
**Affected versions**:
odoo 16.0
1. install queue_job
2. run odoo
3. exception outputs in terminal

**Comment by RichardThunder** [comment]
This is my config, according to document
[options]
workers = 6
server_wide_modules = web,queue_job

[queue_job]
channels = root:2

**Comment by RichardThunder** [comment]
system: macos 13.4
python: 3.9.16

**Comment by pedrobaeza** [comment]
This is not related to module `queue_job`, but your reverse proxy configuration. Without the module, you'll find the same error. Check Odoo docs.

**Comment by markoppp** [comment]
Hi @pedrobaeza , I have the same issue here with the same setup. ODOO runs on http://localhost:8069, so I have no reverse proxy. What could be your suggestion to me? How to fix it?

Hi @RichardThunder !
I am having the same issue. Also on OSX in my dev environment. Could you please share you solution for the problem?

**Comment by RichardThunder** [comment]
I don't have reverse proxy,too. I have spent a lot of time on this issue, but didn't find a solution to this problem. However, this issue doesn't affect 
normal use, so I finally quit.

**Comment by markoppp** [comment]
@RichardThunder do not quit!!! Here is a solution!!!

In file `odoo-distributions/odoo16/addons/bus/websocket.py` line 814. Make it like this:

```
Websocket(request.httprequest.environ['werkzeug.socket'], request.session),
```

and it will work

**Comment by RichardThunder** [comment]
thank you for your solution

**Comment by simahawk** [comment]
FTR this problem does not sound related at all to queue_job.
Additionally, I recommend to not modify the odoo code directly in your code base. If you spotted a bug open an issue on odoo/odoo or a PR if you have the solution.

**Comment by ghofrane7** [comment]
@markoppp Thank you for your solution, it really matters. In fact, the error doesn't detected but the websocket doesn't work as it should do.. When I send a message in OdooChat wouldn't be shown in recipient chat.. 
Any suggestion for this bug please !
Thank you in advance.
