### ISSUE TITLE
installation not possible in odoo 16

### ISSUE THREAD

**Issue by scwall** [OCA/queue#554]
## Module
queue_job
## Describe the bug
installation not possible

## To Reproduce
**Affected versions**: 16

1. Click install module

**Expected behavior**
```
raceback (most recent call last):
  File "/opt/odoo_test/odoo16/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/service/model.py", line 133, in retrying
    result = func()
             ^^^^^^
  File "/opt/odoo_test/odoo16/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/opt/odoo_test/odoo16/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-14>", line 2, in new
  File "/opt/odoo_test/odoo16/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo_test/odoo16/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/modules/loading.py", line 197, in load_module_graph
    model_names = registry.load(cr, package)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/modules/registry.py", line 247, in load
    model = cls._build_model(self, cr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo_test/odoo16/odoo/models.py", line 635, in _build_model
    raise TypeError("Model %r inherits from non-existing model %r." % (name, parent))
TypeError: Model 'queue.jobs.to.done' inherits from non-existing model 'queue.requeue.job'.

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://sodooapptest.hsn.local/web/assets/1476-4023fff/web.assets_backend.min.js:983:163)
    at XMLHttpRequest.<anonymous> (http://sodooapptest.hsn.local/web/assets/1476-4023fff/web.assets_backend.min.js:991:13)
```

**Comment by scwall** [comment]
workaround found, I renamed queue_jobs_to_done to zqueue_jobs_to_done so that it loads it last
