### ISSUE TITLE
[11.0]  jobrunner raise exception, when database is dropped from manager

### ISSUE THREAD

**Issue by KarstenK77** [OCA/queue#68]
#https://github.com/odoo/odoo/issues/24788
```
2018-05-17 14:12:58,856 6866 ERROR ? odoo.addons.queue_job.jobrunner.runner: exception: sleeping 5s and retrying
Traceback (most recent call last):
  File "/opt/workspace/ODOO11-ADDON-RESSOURCES/queue/queue_job/jobrunner/runner.py", line 397, in run
    self.wait_notification()
  File "/opt/workspace/ODOO11-ADDON-RESSOURCES/queue/queue_job/jobrunner/runner.py", line 375, in wait_notification
    conn.poll()
psycopg2.OperationalError: SSL connection has been closed unexpectedly
```

**Comment by iaranburu** [comment]
Impacted versions: 11.0

It is played trying to delete a database that has the queue_job module installed and having previously imported something.

Steps: 
- In FF. Goto /web/database/manager and delete a db from list
- get an error 500
