### ISSUE TITLE
[10.0] Error when creating channels from UI

### ISSUE THREAD

**Issue by xtof-osd** [OCA/queue#84]
Installed queue_job from git branch 10.0 on a 10.0 Odoo (from debian package).

When trying to create a new channel from UI, an exception is raised (see stacktrace below)

It does not prevent creating new channels but is confusing.

--
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5498, in onchange
    value = record[name]
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5232, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 917, in __get__
    self.determine_draft_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1038, in determine_draft_value
    self._compute_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 972, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/addons/10.0/queue/queue_job/models/queue_job.py", line 324, in _compute_complete_name
    record.complete_name = '.'.join(reversed(parts))
TypeError: sequence item 0: expected string, bool found

**Comment by simahawk** [comment]
channel name, parent channel? Please, provide full info on what you did.
Also, are you able to reproduce the error here?
https://runbot.odoo-community.org/runbot/repo/github-com-oca-queue-230

**Comment by Gokulakannanaj** [comment]
This error message displayed when i clicking create button of Channels
