### ISSUE TITLE
Execution and Creation Issue

### ISSUE THREAD

**Issue by Gokulakannanaj** [OCA/queue#85]
First of all sorry for my poor communication
1. When i clicking create button of Channels it throws the error like got boolean instead of string.
2. Function not called (It's always in pending status)

Thanks.

**Comment by Gokulakannanaj** [comment]
While starting with odoo like --load=web,queue_job --workers=6

Traceback (most recent call last):
  File "/home/trail/web11/dev/trail-web/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/trail/web11/dev/trail-web/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/trail/web11/dev/trail-web/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/trail/web11/dev/trail-web/odoo/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable

**Comment by guewen** [comment]
It is unrelated to queue_job, it is because you didn't properly configure a reverse proxy in front of Odoo, redirecting the /longpolling urls to port 8071.

https://www.google.com/search?client=ubuntu&channel=fs&q=odoo+bus+unavailable&ie=utf-8&oe=utf-8

**Comment by Gokulakannanaj** [comment]
👍
